Snazzy Swizzle
Wire-Network/wire-docs pull request #2
Opened 2024-10-10 21:58 UTC by imjakechapman

- [x] Added TailwindCSS
- [x] Created Wire tailwind config based on css variables in wire.network/foundation repos
- [x] Swizzled Anything to do with Navbar and Primary Layout
- [x] Added Footer component from wire network/foundation sites
- [x] Added lucid-react for better icons across the docs site (github, sun/moon, menu and close only currently used)

2024-10-10 22:00 UTC, imjakechapman commented
https://www.loom.com/share/25558018449c4212ad830556f7b82be3

<img width="1728" alt="Screenshot 2024-10-10 at 2 59 41 PM" src="https://github.com/user-attachments/assets/f238ce98-4488-495f-9b0d-a33a94db2056">
<img width="1728" alt="Screenshot 2024-10-10 at 3 00 05 PM" src="https://github.com/user-attachments/assets/1a013f49-0e89-466c-8cdf-e927c1078528">

2024-10-11 13:07 UTC, bearcubsvet commented
@imjakechapman looks like formatting of .md and .mdx got affected by swizzling components 

**Current:** 

<img width="741" alt="Screenshot 2024-10-11 at 9 03 12 AM" src="https://github.com/user-attachments/assets/af800108-287f-4d9f-9be6-461bbe5da500">
<img width="1230" alt="Screenshot 2024-10-11 at 9 03 24 AM" src="https://github.com/user-attachments/assets/508fbc8c-ed17-4f1c-84d7-661963cbe919">

**Desired:** 

<img width="1154" alt="Screenshot 2024-10-11 at 9 05 30 AM" src="https://github.com/user-attachments/assets/32e38246-43f0-41b7-9f7e-850c7579f257">
<img width="1052" alt="Screenshot 2024-10-11 at 9 05 37 AM" src="https://github.com/user-attachments/assets/f499bf4e-e409-48b5-9936-cfc4fcc35a9f">

2024-10-11 13:11 UTC, bearcubsvet requested changes
see my PR comment

2024-10-11 18:28 UTC, bearcubsvet approved these changes

2024-10-11 18:28 UTC, merged